#!/bin/bash
set -e

branch=$(git symbolic-ref --short HEAD)

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo -e "\033[0;31mError: Direct commits to '$branch' are not allowed.\033[0m"
  exit 1
fi
